# Generated by Django 4.2.11 on 2024-07-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_address_zip'),
    ]

    operations = [
        migrations.RunSQL("""
                        insert into store_collection (id, title, featured_product_id)
                            values  (2, 'Grocery', null),
                                    (3, 'Beauty', null),
                                    (4, 'Cleaning', null),
                                    (5, 'Stationary', null),
                                    (6, 'Pets', null),
                                    (7, 'Baking', null),
                                    (8, 'Spices', null),
                                    (9, 'Toys', null),
                                    (10, 'Magazines', null)
                          """,
                          """
                            delete from store_collection
                        """)
    ]
